<?xml version="1.0" encoding="UTF-8"?>
<!--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Legal Notices

SWIFT SCRL@2016. All rights reserved.

This schema is a component of MyStandards, the SWIFT collaborative Web application used to manage
standards definitions and industry usage.

This is a licensed product, which may only be used and distributed in accordance with MyStandards License
Terms as specified in MyStandards Service Description and the related Terms of Use.

Unless otherwise agreed in writing with SWIFT SCRL, the user has no right to:
 - authorise external end users to use this component for other purposes than their internal use.
 - remove, alter, cover, obfuscate or cancel from view any copyright or other proprietary rights notices appearing in this physical medium.
 - re-sell or authorise another party e.g. software and service providers, to re-sell this component.

This component is provided 'AS IS'. SWIFT does not give and excludes any express or implied warranties
with respect to this component such as but not limited to any guarantee as to its quality, supply or availability.

Any and all rights, including title, ownership rights, copyright, trademark, patents, and any other intellectual 
property rights of whatever nature in this component will remain the exclusive property of SWIFT or its 
licensors.

Trademarks
SWIFT is the trade name of S.W.I.F.T. SCRL.
The following are registered trademarks of SWIFT: the SWIFT logo, SWIFT, SWIFTNet, SWIFTReady, Accord, Sibos, 3SKey, Innotribe, the Standards Forum logo, MyStandards, and SWIFT Institute.
Other product, service, or company names in this publication are trade names, trademarks, or registered trademarks of their respective owners.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Group: ESMA
Collection: EMIR Refit - Outgoing Messages - FINAL - V1.1.0
Usage Guideline: auth.092.001.04_ESMAUG_DATREJ_1.0.0
Base Message: auth.092.001.04
Date of publication: 02 November 2023
URL: https://www2.swift.com/mystandards/#/mp/mx/_dTj_0HltEe6cZfzZFKLwyg/_CshaVXluEe6cZfzZFKLwyg
Description: The DerivativesTradeRejectionStatisticalReport message is sent by the trade repository (TR) to the report submitting entity, identifying the transactions rejected and the reasons for a rejection.
Generated by the MyStandards web platform [https://www.swift.com/mystandards] on 2023-11-02T11:55:30+00:00
-->
<!---->
<xs:schema xmlns="urn:iso:std:iso:20022:tech:xsd:auth.092.001.04" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:iso:std:iso:20022:tech:xsd:auth.092.001.04">
    <xs:element name="Document" type="Document"/>
    <xs:complexType name="CollateralPortfolioCode5Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">CollateralPortfolioCode5Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the unique codes identifying the portfolio.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Prtfl" type="PortfolioCode3Choice">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Portfolio</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the unique code assigned by the reporting counterparty to the portfolio if the collateral is posted on a portfolio basis.&#13;
&#13;
Usage:&#13;
NoPortfolio is reported if the collateralisation was performed on a transaction level basis, or if there is no collateral agreement or if no collateral is posted or received.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="CounterpartyData92__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">CounterpartyData92__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Data specific to counterparties and related fields.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="RptgCtrPty" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReportingCounterparty</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of the reporting counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="RptSubmitgNtty" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReportSubmittingEntity</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code identifying the entity which submits the report. In the case where submission of the report has been delegated to a third party or to the other counterparty, a unique code identifying that entity.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="NttyRspnsblForRpt" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">EntityResponsibleForReport</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code identifying that counterparty in the case where a financial counterparty is responsible for reporting on behalf of the other counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="CountryCode">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">CountryCode</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Code to identify a country, a dependency, or another area of particular geopolitical interest, on the basis of country names obtained from the United Nations (ISO 3166, Alpha-2 code).</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="DateAndDateTime2Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DateAndDateTime2Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Choice between a date or a date and time format.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Dt" type="ISODate">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Date</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specified date.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:simpleType name="DerivativeEventType3Code__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DerivativeEventType3Code__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Explanation or reason for the action being taken on the transaction reporting.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="ALOC">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Allocation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Allocation event, where an existing derivative is allocated to different counterparties and reported as new derivatives.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CLRG">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Clearing</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Process in which a CCP interposes itself between the counterparties to the contract becoming the buyer to the counterparty that was a seller and the seller to the counterparty that was a buyer.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="COMP">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Compression</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Compression or post-trade risk reduction exercise.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CORP">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CorporateAction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Result of a corporate action.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CREV">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CreditEvent</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Applies only to credit derivatives. A credit event that results in a termination or modification of a derivative, at a trade or position level.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ETRM">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">EarlyTermination</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Termination of an existing derivative transaction prior to scheduled termination or maturity date.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="EXER">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Exercise</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">The exercise of an option or a swaption by one counterparty of the transaction, fully or partially. </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="INCP">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">InclusionInPosition</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Inclusion of an ETD or CFD into a position, where an existing derivative is terminated and either a new position is created or the notional of an existing position is modified.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="NOVA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Novation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">The replacement of a party to a derivative contract with another party giving rise to a new derivative contract.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="TRAD">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Trade</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Conclusion of a derivative or renegotiation of its terms that does not result in change of a counterparty.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="UPDT">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Update</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Outstanding derivative is updated to comply with the revised requirements on reporting.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="DerivativesTradeRejectionStatisticalReportV04">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DerivativesTradeRejectionStatisticalReportV04</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">The DerivativesTradeRejectionStatisticalReport message is sent by the trade repository (TR) to the report submitting entity, identifying the transactions rejected and the reasons for a rejection.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="RjctnSttstcs" type="StatisticsPerCounterparty18Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">RejectionStatistics</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information on rejections of derivative transactions.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DetailedReportStatistics7">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedReportStatistics7</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed statistics on reports.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="TtlNbOfRpts" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfReports</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of reports sent or received.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfRptsAccptd" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfReportsAccepted</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of reports accepted.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfRptsRjctd" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfReportsRejected</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of reports rejected.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="NbOfRptsRjctdPerErr" type="NumberOfTransactionsPerValidationRule6">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfReportsRejectedPerError</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of reports rejected per error code.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DetailedStatisticsPerCounterparty19__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedStatisticsPerCounterparty19__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information on statistics per combination of counterparties.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="RefDt" type="ISODate">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReferenceDate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Reference date for statistics collection.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfRpts" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfReports</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of reports sent or received.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfRptsAccptd" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfReportsAccepted</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of reports accepted.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfRptsRjctd" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfReportsRejected</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of reports rejected.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfTxs" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfTransactions</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of reports sent or received.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfTxsAccptd" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfTransactionsAccepted</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of transactions accepted.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfTxsRjctd" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfTransactionsRejected</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of transactions rejected.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="RjctnSttstcs" type="RejectionStatistics9__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">RejectionStatistics</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information on rejections for derivatives submitted to trade repositories and failed to pass validations.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DetailedTransactionStatistics30__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedTransactionStatistics30__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information about number of transactions accepted and rejected and the reasons of the rejections.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="TtlNbOfTxs" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfTransactions</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of reports sent or received.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfTxsAccptd" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfTransactionsAccepted</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of transactions accepted.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TtlNbOfTxsRjctd" type="Max20PositiveNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalNumberOfTransactionsRejected</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Total number of transactions rejected.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="500000" minOccurs="0" name="TxsRjctnsRsn" type="RejectionReason71__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionsRejectionsReason</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Details on transactions rejected per error code.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DetailedTransactionStatistics7Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedTransactionStatistics7Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information about number of transactions accepted and rejected and the reasons of the rejections.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="DataSetActn" type="ReportPeriodActivity1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DataSetAction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the type of report activity for a specific reporting period.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="DtldSttstcs" type="DetailedTransactionStatistics30__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DetailedStatistics</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information about number of transactions accepted and rejected and the reasons of the rejections.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="Document">
        <xs:sequence>
            <xs:element name="DerivsTradRjctnSttstclRpt" type="DerivativesTradeRejectionStatisticalReportV04"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ExternalValidationRuleIdentification1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ExternalValidationRuleIdentification1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the external validation rule identification scheme name code in the format of character string with a maximum length of 4 characters.&#13;
The list of valid codes is an external code list published separately.&#13;
External code sets can be downloaded from www.iso20022.org.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="4"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="GenericIdentification175__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">GenericIdentification175__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information related to an identification, for example party identification or account identification.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Max72Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification assigned by an institution.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GenericValidationRuleIdentification1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">GenericValidationRuleIdentification1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information for the identification of a validation rule.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a validation rule.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Desc" type="Max350Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Description</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Further information on the validation rule as identified in the Identification.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="SchmeNm" type="ValidationRuleSchemeName1Choice">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SchemeName</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Issr" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Issuer</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Entity that assigns the identification.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ISODate">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ISODate</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:date"/>
    </xs:simpleType>
    <xs:simpleType name="ISODateTime">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ISODateTime</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
Note on the time format:
1) beginning / end of calendar day
00:00:00 = the beginning of a calendar day
24:00:00 = the end of a calendar day
2) fractions of second in time format
Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:dateTime"/>
    </xs:simpleType>
    <xs:simpleType name="LEIIdentifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">LEIIdentifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Legal Entity Identifier is a code allocated to a party as described in ISO 17442 "Financial Services - Legal Entity Identifier (LEI)".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{18,18}[0-9]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="LegalPersonIdentification1__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">LegalPersonIdentification1__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides the identification of the organisation which is a legal person.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of the legal person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="Max140Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max140Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 140 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="140"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max15NumericText">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max15NumericText</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a numeric string with a maximum length of 15 digits.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,15}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max20PositiveNumber">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max20PositiveNumber</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Number of objects represented as an integer.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="0"/>
            <xs:totalDigits value="20"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max350Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max350Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 350 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="350"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max35Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max35Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 35 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max52Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max52Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 52 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="52"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max72Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max72Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 72 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="72"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="NaturalPersonIdentification2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NaturalPersonIdentification2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Identifies a natural person through identification number, name and domicile.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="GenericIdentification175__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of the natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NaturalPersonIdentification3__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NaturalPersonIdentification3__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Identifies a natural person through identification number, name and domicile.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="NaturalPersonIdentification2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of the natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Ctry" type="CountryCode">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Country</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Code of country of residence of a natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="NotApplicable1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NotApplicable1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies special purpose codes.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="4"/>
            <xs:enumeration value="NOAP">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NotApplicable</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Not applicable (N/A).</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="NumberOfTransactionsPerValidationRule6">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NumberOfTransactionsPerValidationRule6</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Number of individual reports or transactions received / sent, detailed per validation rule.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="DtldNb" type="Max15NumericText">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DetailedNumber</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of individual reports or transactions sent / received, detailed per status.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="RptSts" type="RejectionReason70">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReportStatus</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Common validation rule for all individual reports received.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OrganisationIdentification15Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification15Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides the identification of the organisation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="LEI" type="LEIIdentifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">LEI</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification is done through the use of legal entity identifier code.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Othr" type="OrganisationIdentification38__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Other</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification of an organisation, using a client code or a business identification code.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="OrganisationIdentification38__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification38__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Identifies an organisation through client identification, a name and a domicile.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="GenericIdentification175__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of the organisation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PartyIdentification248Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PartyIdentification248Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides the identification of the organisation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Lgl" type="LegalPersonIdentification1__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Legal</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Party is a legal person.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Ntrl" type="NaturalPersonIdentification3__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Natural</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Party is a natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="PortfolioCode3Choice">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PortfolioCode3Choice</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Element is a choice between a known portfolio code and a code applicable when the code is unknown.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Cd" type="Max52Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Code</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code determined by the reporting counterparty to identify the portfolio if collateral is reported on a portfolio basis.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NoPrtfl" type="NotApplicable1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NoPortfolio</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Collateralisation was performed on a transaction level basis or if the collateral portfolio code is not known at the time of reporting.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="RejectionReason70">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">RejectionReason70</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides reasons of rejecting transactions.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="MsgRptId" type="Max140Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MessageReportIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of the report.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Sts" type="ReportingMessageStatus2Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Status</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information on status of submitted transactions.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="DtldVldtnRule" type="GenericValidationRuleIdentification1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DetailedValidationRule</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Acceptance criteria of the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RejectionReason71__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">RejectionReason71__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides reasons of rejecting transactions.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="TxId" type="TradeTransactionIdentification24__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Sts" type="ReportingMessageStatus2Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Status</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information on status of submitted transactions.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="DtldVldtnRule" type="GenericValidationRuleIdentification1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DetailedValidationRule</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Acceptance criteria of the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="RejectionStatistics9__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">RejectionStatistics9__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information on rejections for derivatives submitted to trade repositories and failed to pass validations.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="CtrPtyId" type="CounterpartyData92__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CounterpartyIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Data specific to counterparties and related fields.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="RptSttstcs" type="DetailedReportStatistics7">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReportStatistics</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Information about accepted and rejected reports and the reasons of rejection.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="DerivSttstcs" type="DetailedTransactionStatistics7Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DerivativeStatistics</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information on rejections for derivatives submitted to trade repositories and failed to pass data validations.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ReportPeriodActivity1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ReportPeriodActivity1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the type of report activity for a specific reporting period.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="NOTX">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NoTransaction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">No transaction has been identified during the period.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ReportingMessageStatus2Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ReportingMessageStatus2Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the status of a whole message processing.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="ACPT">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Accepted</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Whole message has been accepted.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="RJCT">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Rejected</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Message has been rejected.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="INCF">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">IncorrectFilename</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">File containing the report has an incorrect filename.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CRPT">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CorruptedFile</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">File containing the report is corrupted.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="NAUT">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NotAuthorised</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Message was rejected due to authorisation/permission issues.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="StatisticsPerCounterparty18Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">StatisticsPerCounterparty18Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Statistics per counterparty reporting under the local regulation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="DataSetActn" type="ReportPeriodActivity1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DataSetAction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Where no reporting data are available, this field should be set so that a valid reference data file can be submitted to the competent authority as per submission requirements.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Rpt" type="DetailedStatisticsPerCounterparty19__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Report</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed statistics per counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="TradeTransactionIdentification24__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">TradeTransactionIdentification24__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides details on transaction and conducting counterparty.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="ActnTp" type="TransactionOperationType10Code__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ActionType</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indication of the action type of the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="RptgTmStmp" type="ISODateTime">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReportingTimeStamp</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the date and time of the submission of the report to the trade repository.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="DerivEvtTp" type="DerivativeEventType3Code__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DerivativeEventType</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Classification of derivative event type.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="DerivEvtTmStmp" type="DateAndDateTime2Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DerivativeEventTimeStamp</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the time stamp of a derivative event.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="OthrCtrPty" type="PartyIdentification248Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OtherCounterparty</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code identifying the entity with which the reporting counterparty concluded the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="UnqIdr" type="UniqueTransactionIdentifier2Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UniqueIdentifier</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Choice between a Unique Transaction Identifier (UTI) or a proprietary identifier as agreed with the counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="CollPrtflCd" type="CollateralPortfolioCode5Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CollateralPortfolioCode</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique codes identifying the portfolio.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TransactionOperationType10Code__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">TransactionOperationType10Code__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the transaction operation action type.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="COMP">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Compression</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Transaction is a compression.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CORR">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Correction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Transaction corrects errors in a previously sent transaction.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="EROR">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Error</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Cancellation of a wrongly submitted entire report in case the contract never came into existence or was not subject to regulatory reporting requirements but was reported to a regulatory authority by mistake or a cancellation of duplicate report.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="MODI">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Modification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Transaction modifies in a previously sent transaction.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="NEWT">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NewTransaction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Transaction is a new transaction.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="POSC">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">PositionComponent</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Contract to be reported as a new trade and included in a separate position report on the same day.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="REVI">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Revive</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Re-opening of a derivative, at a trade or position level, that was cancelled or terminated by mistake.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="TERM">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Termination</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Closing of an existing transaction because of a new event (for example: Compression, Novation). This does not apply to transactions that terminate at contractual maturity date.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="VALU">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ValuationUpdate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Update of a contract valuation or collateral.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="MARU">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MarginUpdate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the report of the collateral data or of their modifications, but not the corrections of the previously reported collateral details.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="UTIIdentifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">UTIIdentifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique Transaction Identifier (UTI). Unique number allocated to a financial transaction as agreed among the parties and/or within the regulatory system under which it is formed. The UTI is described in the latest edition of the international standard ISO 23897:2020.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{18}[0-9]{2}[A-Z0-9]{0,32}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="UniqueTransactionIdentifier2Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">UniqueTransactionIdentifier2Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Element is a choice between a standard identifier and a proprietary code.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="UnqTxIdr" type="UTIIdentifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UniqueTransactionIdentifier</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique trade identifier (UTI) as agreed with the counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Prtry" type="GenericIdentification175__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Proprietary</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Trade identifier expressed in a proprietary notation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="ValidationRuleSchemeName1Choice">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ValidationRuleSchemeName1Choice</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Identifies a name of the identification scheme.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Cd" type="ExternalValidationRuleIdentification1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Code</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme, in a coded form as published in an external list.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Prtry" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Proprietary</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme, in a free text form.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
</xs:schema>
