<?xml version="1.0" encoding="UTF-8"?>
<!--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Legal Notices

SWIFT SCRL@2016. All rights reserved.

This schema is a component of MyStandards, the SWIFT collaborative Web application used to manage
standards definitions and industry usage.

This is a licensed product, which may only be used and distributed in accordance with MyStandards License
Terms as specified in MyStandards Service Description and the related Terms of Use.

Unless otherwise agreed in writing with SWIFT SCRL, the user has no right to:
 - authorise external end users to use this component for other purposes than their internal use.
 - remove, alter, cover, obfuscate or cancel from view any copyright or other proprietary rights notices appearing in this physical medium.
 - re-sell or authorise another party e.g. software and service providers, to re-sell this component.

This component is provided 'AS IS'. SWIFT does not give and excludes any express or implied warranties
with respect to this component such as but not limited to any guarantee as to its quality, supply or availability.

Any and all rights, including title, ownership rights, copyright, trademark, patents, and any other intellectual 
property rights of whatever nature in this component will remain the exclusive property of SWIFT or its 
licensors.

Trademarks
SWIFT is the trade name of S.W.I.F.T. SCRL.
The following are registered trademarks of SWIFT: the SWIFT logo, SWIFT, SWIFTNet, SWIFTReady, Accord, Sibos, 3SKey, Innotribe, the Standards Forum logo, MyStandards, and SWIFT Institute.
Other product, service, or company names in this publication are trade names, trademarks, or registered trademarks of their respective owners.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Group: ESMA
Collection: EMIR Refit - Outgoing Messages - FINAL - V1.1.0
Usage Guideline: auth.106.001.01_ESMAUG_DATWRN_1.1.0
Base Message: auth.106.001.01
Date of publication: 02 November 2023
URL: https://www2.swift.com/mystandards/#/mp/mx/_dTj_0HltEe6cZfzZFKLwyg/_Fak8BXluEe6cZfzZFKLwyg
Description: The DerivativesTradeWarningsReport is sent by the trade repository (TR) to the authority or made available by the trade repository (TR) to the report submitting entity and the reporting counterparty as well as the entity responsible for reporting, if applicable.
Generated by the MyStandards web platform [https://www.swift.com/mystandards] on 2023-11-02T11:55:30+00:00
-->
<!---->
<xs:schema xmlns="urn:iso:std:iso:20022:tech:xsd:auth.106.001.01" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:iso:std:iso:20022:tech:xsd:auth.106.001.01">
    <xs:element name="Document" type="Document"/>
    <xs:complexType name="AbnormalValuesData4__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">AbnormalValuesData4__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information about derivatives that were received on the day of generation of the report with action type ‘New’, ‘Position component’, ‘Modification’ or ‘Correction’ whose notional amount is greater than a threshold for that class of derivatives.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="CtrPtyId" type="CounterpartyData92__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CounterpartyIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Data specific to counterparties and related fields.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfDerivsRptd" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfDerivativesReported</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of reported derivatives.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfDerivsRptdWthOtlrs" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfDerivativesReportedWithOutliers</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of reported derivatives with outliers.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="TxDtls" type="AbnormalValuesTransactionData2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionDetails</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Details on abnormal values per transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AbnormalValuesTransactionData2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">AbnormalValuesTransactionData2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information about derivatives that were received on the day of generation of the report with action type ‘New’, ‘Position component’, ‘Modification’ or ‘Correction’ whose notional amount is greater than a threshold for that class of derivatives.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="TxId" type="TradeTransactionIdentification24__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NtnlAmt" type="NotionalAmountLegs5__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NotionalAmount</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Posting of an item to a cash account, in the context of a cash transaction, that results in an increase or decrease to the balance of the account.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="NtnlQty" type="NotionalQuantityLegs5__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NotionalQuantity</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates for each leg of the transaction the total notional quantity of the underlying asset for the term of the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ActiveCurrencyCode">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ActiveCurrencyCode</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A code allocated to a currency by a Maintenance Agency under an international identification scheme as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3,3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ActiveOrHistoricCurrencyAnd19DecimalAmount_SimpleType">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="19"/>
            <xs:totalDigits value="25"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ActiveOrHistoricCurrencyAnd19DecimalAmount">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ActiveOrHistoricCurrencyAnd19DecimalAmount</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A number of monetary units specified in an active or a historic currency where the unit of currency is explicit and compliant with ISO 4217.</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="ActiveOrHistoricCurrencyAnd19DecimalAmount_SimpleType">
                <xs:attribute name="Ccy" type="ActiveCurrencyCode" use="required">
                    <xs:annotation>
                        <xs:documentation source="Name" xml:lang="EN">Currency</xs:documentation>
                        <xs:documentation source="Definition" xml:lang="EN">Medium of exchange of value.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="ActiveOrHistoricCurrencyAnd5DecimalAmount_SimpleType">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="5"/>
            <xs:totalDigits value="25"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="ActiveOrHistoricCurrencyAnd5DecimalAmount">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ActiveOrHistoricCurrencyAnd5DecimalAmount</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A number of monetary units specified in an active or a historic currency where the unit of currency is explicit and compliant with ISO 4217.</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="ActiveOrHistoricCurrencyAnd5DecimalAmount_SimpleType">
                <xs:attribute name="Ccy" type="ActiveCurrencyCode" use="required">
                    <xs:annotation>
                        <xs:documentation source="Name" xml:lang="EN">Currency</xs:documentation>
                        <xs:documentation source="Definition" xml:lang="EN">Medium of exchange of value.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="ActiveOrHistoricCurrencyCode">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ActiveOrHistoricCurrencyCode</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3,3}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="AmountAndDirection106">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">AmountAndDirection106</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Posting of an item to a cash account, in the context of a cash transaction, that results in an increase or decrease to the balance of the account.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Amt" type="ActiveOrHistoricCurrencyAnd19DecimalAmount">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Amount</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Amount of money in the cash entry.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Sgn" type="PlusOrMinusIndicator">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Sign</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates that the amount value is positive or negative.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AmountAndDirection106__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">AmountAndDirection106__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Posting of an item to a cash account, in the context of a cash transaction, that results in an increase or decrease to the balance of the account.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Amt" type="ActiveOrHistoricCurrencyAnd5DecimalAmount">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Amount</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Amount of money in the cash entry.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Sgn" type="PlusOrMinusIndicator">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Sign</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates that the amount value is positive or negative.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AmountAndDirection106__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">AmountAndDirection106__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Posting of an item to a cash account, in the context of a cash transaction, that results in an increase or decrease to the balance of the account.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Amt" type="ActiveOrHistoricCurrencyAnd5DecimalAmount">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Amount</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Amount of money in the cash entry.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="CounterpartyData92__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">CounterpartyData92__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Data specific to counterparties and related fields.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="RptgCtrPty" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReportingCounterparty</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of the reporting counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="RptSubmitgNtty" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReportSubmittingEntity</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code identifying the entity which submits the report. In the case where submission of the report has been delegated to a third party or to the other counterparty, a unique code identifying that entity.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="NttyRspnsblForRpt" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">EntityResponsibleForReport</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code identifying that counterparty in the case where a financial counterparty is responsible for reporting on behalf of the other counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="CountryCode">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">CountryCode</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Code to identify a country, a dependency, or another area of particular geopolitical interest, on the basis of country names obtained from the United Nations (ISO 3166, Alpha-2 code).</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="DateAndDateTime2Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DateAndDateTime2Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Choice between a date or a date and time format.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="DtTm" type="ISODateTime">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DateTime</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specified date and time.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="DateAndDateTime2Choice__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DateAndDateTime2Choice__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Choice between a date or a date and time format.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Dt" type="ISODate">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Date</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specified date.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:simpleType name="DerivativeEventType3Code__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DerivativeEventType3Code__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Explanation or reason for the action being taken on the transaction reporting.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="ALOC">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Allocation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Allocation event, where an existing derivative is allocated to different counterparties and reported as new derivatives.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CLRG">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Clearing</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Process in which a CCP interposes itself between the counterparties to the contract becoming the buyer to the counterparty that was a seller and the seller to the counterparty that was a buyer.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="COMP">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Compression</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Compression or post-trade risk reduction exercise.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CORP">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CorporateAction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Result of a corporate action.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CREV">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CreditEvent</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Applies only to credit derivatives. A credit event that results in a termination or modification of a derivative, at a trade or position level.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ETRM">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">EarlyTermination</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Termination of an existing derivative transaction prior to scheduled termination or maturity date.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="EXER">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Exercise</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">The exercise of an option or a swaption by one counterparty of the transaction, fully or partially. </xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="INCP">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">InclusionInPosition</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Inclusion of an ETD or CFD into a position, where an existing derivative is terminated and either a new position is created or the notional of an existing position is modified.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="NOVA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Novation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">The replacement of a party to a derivative contract with another party giving rise to a new derivative contract.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="TRAD">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Trade</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Conclusion of a derivative or renegotiation of its terms that does not result in change of a counterparty.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="UPDT">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Update</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Outstanding derivative is updated to comply with the revised requirements on reporting.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="DerivativesTradeWarningsReportV01">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DerivativesTradeWarningsReportV01</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">The DerivativesTradeWarningsReport is sent by the trade repository (TR) to the authority or made available by the trade repository (TR) to the report submitting entity and the reporting counterparty as well as the entity responsible for reporting, if applicable.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="WrnngsSttstcs" type="StatisticsPerCounterparty16Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">WarningsStatistics</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information on missing valuations of outstanding derivatives, missing margin information of outstanding derivatives, as well as on abnormal values reported in the fields.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DetailedAbnormalValuesStatistics4Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedAbnormalValuesStatistics4Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information of abnormal values.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="DataSetActn" type="ReportPeriodActivity1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DataSetAction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the type of report activity for a specific reporting period.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Rpt" type="DetailedTransactionStatistics28__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Report</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information on statistics per combination of counterparties.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="DetailedMissingMarginInformationStatistics4Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedMissingMarginInformationStatistics4Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information of no margin or outdated margin information.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="DataSetActn" type="ReportPeriodActivity1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DataSetAction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the type of report activity for a specific reporting period.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Rpt" type="DetailedTransactionStatistics26__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Report</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information on statistics per combination of counterparties.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="DetailedMissingValuationsStatistics4Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedMissingValuationsStatistics4Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information of no valuation or outdated valuation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="DataSetActn" type="ReportPeriodActivity1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DataSetAction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the type of report activity for a specific reporting period.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Rpt" type="DetailedTransactionStatistics27__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Report</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information on statistics per combination of counterparties.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="DetailedStatisticsPerCounterparty17__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedStatisticsPerCounterparty17__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information on statistics per combination of counterparties.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="RefDt" type="ISODate">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReferenceDate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Reference date for statistics collection.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="MssngValtn" type="DetailedMissingValuationsStatistics4Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MissingValuation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information of outstanding derivatives for which the valuation was not reported or the valuation reported is more than fourteen calendar days earlier than the date for which the report was generated shall be included in the report of missing valuations at the end of the day.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="MssngMrgnInf" type="DetailedMissingMarginInformationStatistics4Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MissingMarginInformation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information of the outstanding derivatives for which no margin information has been reported, or the margin information that was reported is dated more than fourteen calendar days earlier than the day.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="AbnrmlVals" type="DetailedAbnormalValuesStatistics4Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">AbnormalValues</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information of the derivatives that were received on the day of generation of the report with action type ‘New’, ‘Position component’, ‘Modification’ or ‘Correction’ whose notional amount is greater than a threshold for that class of derivatives.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DetailedTransactionStatistics26__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedTransactionStatistics26__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information about outstanding derivatives, outstanding derivatives with no margin and outstanding derivatives with outdated margin.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="NbOfOutsdngDerivs" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivatives</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivsWthNoMrgnInf" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivativesWithNoMarginInformation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives with no margin information.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivsWthOutdtdMrgnInf" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivativesWithOutdatedMarginInformation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives with outdated margin information.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="500000" minOccurs="1" name="Wrnngs" type="MissingMarginData2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Warnings</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Details of the outstanding derivatives for which no margin information has been reported, or the margin information that was reported is dated more than fourteen calendar days earlier than the day.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DetailedTransactionStatistics27__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedTransactionStatistics27__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information about outstanding derivatives, outstanding derivatives with no valuation and outstanding derivatives with outdated valuation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="NbOfOutsdngDerivs" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivatives</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivsWthNoValtn" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivativesWithNoValuation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives for which valuation amount was never reported.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivsWthOutdtdValtn" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivativesWithOutdatedValuation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives with outdated valuation.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="500000" minOccurs="1" name="Wrnngs" type="MissingValuationsData2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Warnings</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Details of outstanding derivatives for which the valuation was not reported or the valuation reported is more than fourteen calendar days earlier than the date for which the report was generated shall be included in the report of missing valuations at the end of the day.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DetailedTransactionStatistics28__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">DetailedTransactionStatistics28__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information about reported derivatives and reported derivatives with outliers.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="NbOfDerivsRptd" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfDerivativesReported</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of reported derivatives.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfDerivsRptdWthOtlrs" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfDerivativesReportedWithOutliers</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of reported derivatives with outliers.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="500000" minOccurs="1" name="Wrnngs" type="AbnormalValuesData4__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Warnings</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Details of abnormal values.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Document">
        <xs:sequence>
            <xs:element name="DerivsTradWrnngsRpt" type="DerivativesTradeWarningsReportV01"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GenericIdentification175__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">GenericIdentification175__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information related to an identification, for example party identification or account identification.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Max72Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification assigned by an institution.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ISODate">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ISODate</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A particular point in the progression of time in a calendar year expressed in the YYYY-MM-DD format. This representation is defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:date"/>
    </xs:simpleType>
    <xs:simpleType name="ISODateTime">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ISODateTime</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">A particular point in the progression of time defined by a mandatory date and a mandatory time component, expressed in either UTC time format (YYYY-MM-DDThh:mm:ss.sssZ), local time with UTC offset format (YYYY-MM-DDThh:mm:ss.sss+/-hh:mm), or local time format (YYYY-MM-DDThh:mm:ss.sss). These representations are defined in "XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004" which is aligned with ISO 8601.
Note on the time format:
1) beginning / end of calendar day
00:00:00 = the beginning of a calendar day
24:00:00 = the end of a calendar day
2) fractions of second in time format
Decimal fractions of seconds may be included. In this case, the involved parties shall agree on the maximum number of digits that are allowed.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:dateTime"/>
    </xs:simpleType>
    <xs:simpleType name="LEIIdentifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">LEIIdentifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Legal Entity Identifier is a code allocated to a party as described in ISO 17442 "Financial Services - Legal Entity Identifier (LEI)".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{18,18}[0-9]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="LegalPersonIdentification1__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">LegalPersonIdentification1__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides the identification of the organisation which is a legal person.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of the legal person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="LongFraction5DecimalNumber">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">LongFraction5DecimalNumber</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Number of objects represented as a decimal number, eg, 0.75 or 45.6.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="5"/>
            <xs:totalDigits value="25"/>
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max72Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max72Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 72 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="72"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="MissingMarginData2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">MissingMarginData2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information about the outstanding derivatives for which no margin or outdated margin information has been reported.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="CtrPtyId" type="CounterpartyData92__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CounterpartyIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Data specific to counterparties and related fields.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivs" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivatives</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivsWthNoMrgnInf" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivativesWithNoMarginInformation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives with no margin information.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivsWthOutdtdMrgnInf" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivativesWithOutdatedMarginInformation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives with outdated margin information.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="TxDtls" type="MissingMarginTransactionData2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionDetails</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Details of missing margins per transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MissingMarginTransactionData2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">MissingMarginTransactionData2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information about the outstanding derivatives for which no margin or outdated margin information has been reported.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="TxId" type="TradeTransactionIdentification24__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="CollTmStmp" type="ISODateTime">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CollateralTimeStamp</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the date and time of the last collateral amount determination or calculation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MissingValuationsData2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">MissingValuationsData2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information about the outstanding derivatives for which no valuation or outdated valuation has been reported.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="CtrPtyId" type="CounterpartyData92__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CounterpartyIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Data specific to counterparties and related fields.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivs" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivatives</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivsWthNoValtn" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivativesWithNoValuation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives for which valuation amount was never reported.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="NbOfOutsdngDerivsWthOutdtdValtn" type="Number">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NumberOfOutstandingDerivativesWithOutdatedValuation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of outstanding derivatives with outdated valuation.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="TxDtls" type="MissingValuationsTransactionData2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionDetails</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Details of missing valuations per transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="MissingValuationsTransactionData2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">MissingValuationsTransactionData2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Detailed information about the outstanding derivatives for which no valuation or outdated valuation has been reported.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="TxId" type="TradeTransactionIdentification24__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="ValtnAmt" type="AmountAndDirection106__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ValuationAmount</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Mark-to-market valuation of the contract, or mark-to-model valuation</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="ValtnTmStmp" type="DateAndDateTime2Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ValuationTimeStamp</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Date and time of the valuation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NaturalPersonIdentification2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NaturalPersonIdentification2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Identifies a natural person through identification number, name and domicile.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="GenericIdentification175__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of the natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NaturalPersonIdentification3__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NaturalPersonIdentification3__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Identifies a natural person through identification number, name and domicile.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="NaturalPersonIdentification2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of the natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Ctry" type="CountryCode">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Country</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Code of country of residence of a natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NotionalAmount5__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NotionalAmount5__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Indicates the reference amount from which contractual payments are determined and the schedule applicable to the payments.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Amt" type="AmountAndDirection106__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Amount</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Reference amount from which contractual payments are determined.&#13;
&#13;
Usage: In case of partial terminations, and amortisations and in case of contracts where the notional, due to the characteristics of the contract, varies over time, it shall reflect the remaining notional after the change took place.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="SchdlPrd" type="Schedule11">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SchedulePeriod</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the effective date and end date of the schedule for derivative transactions negotiated in monetary amounts varying throughout the life of the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NotionalAmount6__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NotionalAmount6__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Indicates the reference amount from which contractual payments are determined and the schedule applicable to the payments.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="Amt" type="AmountAndDirection106__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Amount</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Reference amount from which contractual payments are determined.&#13;
&#13;
Usage: In case of partial terminations, and amortisations and in case of contracts where the notional, due to the characteristics of the contract, varies over time, it shall reflect the remaining notional after the change took place.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="SchdlPrd" type="Schedule11">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SchedulePeriod</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the effective date and end date of the schedule for derivative transactions negotiated in monetary amounts varying throughout the life of the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Ccy" type="ActiveOrHistoricCurrencyCode">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Currency</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the currency of the notional amount.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NotionalAmountLegs5__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NotionalAmountLegs5__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Indicates the monetary or converted amount for the derivatives transaction.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="FrstLeg" type="NotionalAmount5__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">FirstLeg</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Notional amount of leg 1 which indicates monetary or converted amount for the derivatives transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="ScndLeg" type="NotionalAmount6__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SecondLeg</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Notional amount of leg 2 which indicates monetary or converted amount for the derivatives transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NotionalQuantity9__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NotionalQuantity9__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Indicates the reference quantity of the transaction and the schedule applicable to the quantity computation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="TtlQty" type="LongFraction5DecimalNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TotalQuantity</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of units of the financial instrument, that is, the nominal value.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Dtls" type="QuantityOrTerm1Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Details</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the schedule or frequency of the derivative transactions.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="NotionalQuantityLegs5__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NotionalQuantityLegs5__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Indicates the notional quantity of the underlying assets.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="FrstLeg" type="NotionalQuantity9__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">FirstLeg</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Aggregate notional quantity of the underlying asset of leg 1 for the term of the transaction. Where the total notional quantity is not known when a new transaction is reported, the total notional quantity is updated as it becomes available. </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="ScndLeg" type="NotionalQuantity9__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SecondLeg</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Aggregate notional quantity of the underlying asset of leg 2 for the term of the transaction. Where the total notional quantity is not known when a new transaction is reported, the total notional quantity is updated as it becomes available. </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="Number">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Number</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Number of objects represented as an integer.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="0"/>
            <xs:totalDigits value="18"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="OrganisationIdentification15Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification15Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides the identification of the organisation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="LEI" type="LEIIdentifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">LEI</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification is done through the use of legal entity identifier code.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="PartyIdentification248Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PartyIdentification248Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides the identification of the organisation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Lgl" type="LegalPersonIdentification1__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Legal</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Party is a legal person.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Ntrl" type="NaturalPersonIdentification3__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Natural</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Party is a natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:simpleType name="PlusOrMinusIndicator">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PlusOrMinusIndicator</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Indicates a positive or negative value.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>
    <xs:complexType name="QuantityOrTerm1Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">QuantityOrTerm1Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Indicates the schedule or frequency of the derivative transactions.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="SchdlPrd" type="Schedule10__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SchedulePeriod</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the effective date and end date of the schedule for derivative transactions negotiated in non-monetary amounts with a notional quantity varying throughout the life of the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:simpleType name="ReportPeriodActivity1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ReportPeriodActivity1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the type of report activity for a specific reporting period.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="NOTX">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NoTransaction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">No transaction has been identified during the period.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="Schedule10__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Schedule10__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Indicates the unadjusted effective and end date of the schedule.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Qty" type="LongFraction5DecimalNumber">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Quantity</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Number of units of the financial instrument, that is, the nominal value.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="UadjstdFctvDt" type="ISODate">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UnadjustedEffectiveDate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the unadjusted date at which obligations under the  derivative transaction come into effect, as included in the confirmation.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="UadjstdEndDt" type="ISODate">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UnadjustedEndDate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the end date agreed in the derivative transaction without adjustment.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Schedule11">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Schedule11</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Indicates the unadjusted effective and end date of the schedule.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="UadjstdFctvDt" type="ISODate">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UnadjustedEffectiveDate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the unadjusted date at which obligations under the  derivative transaction come into effect, as included in the confirmation.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="UadjstdEndDt" type="ISODate">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UnadjustedEndDate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the end date agreed in the derivative transaction without adjustment.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Amt" type="AmountAndDirection106">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Amount</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the price per derivative excluding, where applicable, commission and accrued interest.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="StatisticsPerCounterparty16Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">StatisticsPerCounterparty16Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Statistics per counterparty reporting under the local regulation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="DataSetActn" type="ReportPeriodActivity1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DataSetAction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Specifies the type of report activity for a specific reporting period.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Rpt" type="DetailedStatisticsPerCounterparty17__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Report</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Detailed information on statistics per combination of counterparties.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="TradeTransactionIdentification24__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">TradeTransactionIdentification24__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides details on transaction and conducting counterparty.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="OthrCtrPty" type="PartyIdentification248Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OtherCounterparty</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code identifying the entity with which the reporting counterparty concluded the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="UnqIdr" type="UniqueTransactionIdentifier2Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UniqueIdentifier</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Choice between a Unique Transaction Identifier (UTI) or a proprietary identifier as agreed with the counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TradeTransactionIdentification24__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">TradeTransactionIdentification24__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides details on transaction and conducting counterparty.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="ActnTp" type="TransactionOperationType10Code__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ActionType</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indication of the action type of the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="RptgTmStmp" type="ISODateTime">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReportingTimeStamp</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the date and time of the submission of the report to the trade repository.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="DerivEvtTp" type="DerivativeEventType3Code__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DerivativeEventType</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Classification of derivative event type.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="DerivEvtTmStmp" type="DateAndDateTime2Choice__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DerivativeEventTimeStamp</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Indicates the time stamp of a derivative event.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="OthrCtrPty" type="PartyIdentification248Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OtherCounterparty</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code identifying the entity with which the reporting counterparty concluded the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="UnqIdr" type="UniqueTransactionIdentifier2Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UniqueIdentifier</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Choice between a Unique Transaction Identifier (UTI) or a proprietary identifier as agreed with the counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="TransactionOperationType10Code__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">TransactionOperationType10Code__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the transaction operation action type.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="CORR">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Correction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Transaction corrects errors in a previously sent transaction.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="MODI">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Modification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Transaction modifies in a previously sent transaction.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="NEWT">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">NewTransaction</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Transaction is a new transaction.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="POSC">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">PositionComponent</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Contract to be reported as a new trade and included in a separate position report on the same day.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="UTIIdentifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">UTIIdentifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique Transaction Identifier (UTI). Unique number allocated to a financial transaction as agreed among the parties and/or within the regulatory system under which it is formed. The UTI is described in the latest edition of the international standard ISO 23897:2020.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{18}[0-9]{2}[A-Z0-9]{0,32}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="UniqueTransactionIdentifier2Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">UniqueTransactionIdentifier2Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Element is a choice between a standard identifier and a proprietary code.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="UnqTxIdr" type="UTIIdentifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UniqueTransactionIdentifier</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique trade identifier (UTI) as agreed with the counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Prtry" type="GenericIdentification175__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Proprietary</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Trade identifier expressed in a proprietary notation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
</xs:schema>
