<?xml version="1.0" encoding="UTF-8"?>
<!--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Legal Notices

SWIFT SCRL@2016. All rights reserved.

This schema is a component of MyStandards, the SWIFT collaborative Web application used to manage
standards definitions and industry usage.

This is a licensed product, which may only be used and distributed in accordance with MyStandards License
Terms as specified in MyStandards Service Description and the related Terms of Use.

Unless otherwise agreed in writing with SWIFT SCRL, the user has no right to:
 - authorise external end users to use this component for other purposes than their internal use.
 - remove, alter, cover, obfuscate or cancel from view any copyright or other proprietary rights notices appearing in this physical medium.
 - re-sell or authorise another party e.g. software and service providers, to re-sell this component.

This component is provided 'AS IS'. SWIFT does not give and excludes any express or implied warranties
with respect to this component such as but not limited to any guarantee as to its quality, supply or availability.

Any and all rights, including title, ownership rights, copyright, trademark, patents, and any other intellectual 
property rights of whatever nature in this component will remain the exclusive property of SWIFT or its 
licensors.

Trademarks
SWIFT is the trade name of S.W.I.F.T. SCRL.
The following are registered trademarks of SWIFT: the SWIFT logo, SWIFT, SWIFTNet, SWIFTReady, Accord, Sibos, 3SKey, Innotribe, the Standards Forum logo, MyStandards, and SWIFT Institute.
Other product, service, or company names in this publication are trade names, trademarks, or registered trademarks of their respective owners.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Group: ESMA
Collection: EMIR Refit - Outgoing Messages - FINAL - V1.1.0
Usage Guideline: auth.078.001.02_ESMAUG_1.0.0
Base Message: auth.078.001.02
Date of publication: 02 November 2023
URL: https://www2.swift.com/mystandards/#/mp/mx/_dTj_0HltEe6cZfzZFKLwyg/_Kt520XluEe6cZfzZFKLwyg
Description: The SecuritiesFinancingReportingPairingRequest is sent by the trade repository (TR) to the other trade repositories (TRs) in order to identify the trade repository (TR) holding information on a second leg of a given transaction.
Generated by the MyStandards web platform [https://www.swift.com/mystandards] on 2023-11-02T11:55:31+00:00
-->
<!---->
<xs:schema xmlns="urn:iso:std:iso:20022:tech:xsd:auth.078.001.02" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:iso:std:iso:20022:tech:xsd:auth.078.001.02">
    <xs:element name="Document" type="Document"/>
    <xs:complexType name="AgreementType2Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">AgreementType2Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Classification of a master agreement.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Tp" type="MasterAgreementType1Code">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Type</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Name of the identification scheme, in a coded form as published in an external list.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="Document">
        <xs:sequence>
            <xs:element name="SctiesFincgRptgPairgReq" type="SecuritiesFinancingReportingPairingRequestV02"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GenericIdentification175__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">GenericIdentification175__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information related to an identification, for example party identification or account identification.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Max50Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification assigned by an institution.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="ISORestrictedYear">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">ISORestrictedYear</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Year represented by YYYY (ISO 8601)</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:gYear">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2099"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="LEIIdentifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">LEIIdentifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Legal Entity Identifier is a code allocated to a party as described in ISO 17442 "Financial Services - Legal Entity Identifier (LEI)".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{18,18}[0-9]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="MasterAgreement7__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">MasterAgreement7__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information related to a master agreement.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Tp" type="AgreementType2Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Type</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Reference to any master agreement, if existent (such as ISDA Master Agreement; Master Power Purchase and Sale Agreement; International ForEx Master Agreement; European Master Agreement or any local Master Agreements).</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Vrsn" type="ISORestrictedYear">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Version</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Reference to the year of the master agreement version used for the reported trade, if applicable (such as 1992, 2002, etc).</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="OthrMstrAgrmtDtls" type="Max50Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OtherMasterAgreementDetails</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Additional information specifying the other type of the master agreement.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="MasterAgreementType1Code">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">MasterAgreementType1Code</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Reference to the master agreement type under which the counterparties concluded a SFT.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="MRAA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MasterRepurchaseAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Master Repurchase Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="GMRA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">GlobalMasterRepurchaseAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Global Master Repurchase Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="MSLA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MasterSecuritiesLendingAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Master Securities Lending Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="GMSL">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">GlobalMasterSecuritiesLendingAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Global Master Securities Lending Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ISDA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">InternationalSwapsAndDerivativesAssociation</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">International Swaps and Derivatives Association.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="DERP">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DeutscherRahmenvertragFurWertpapierpensionsgeschafte</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Deutscher Rahmenvertrag für Wertpapierpensionsgeschäfte.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CNBR">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ChinaBondRepurchaseMasterAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">China Bond Repurchase Master Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="KRRA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">KoreaFinancialInvestmentAssociationStandardRepurchaseAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Korea Financial Investment Association Standard Repurchase Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CARA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">InvestmentIndustryRegulatoryOrganizationOfCanadaRepurchase</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Investment Industry Regulatory Organization of Canada (IIROC) Repurchase/Reverse Repurchase Transaction Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="FRFB">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ConventionCadreRelativeAuxOperationsDePensionsLivrees</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Convention-Cadre Relative aux Operations de Pensions Livrees.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CHRA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">SwissMasterRepurchaseAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Swiss Master Repurchase Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="DEMA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">GermanMasterAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">German Master Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="JPBR">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">JapaneseMasterAgreementOnTheTransactionWithRepurchaseAgreementOfTheBonds</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Japanese Master Agreement on the Transaction with Repurchase Agreement of the Bonds.&#13;
</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="ESRA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ContratoMarcoDeCompraventaYReportoDeValores</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Contrato Marco de compraventa y Reporto de valores.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="OSLA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OverseasSecuritiesLendingAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Overseas Securities Lending Agreement (OSLA).</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="MEFI">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MasterEquityAndFixedInterestStockLendingAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Master Equity and Fixed Interest Stock Lending Agreement (MEFISLA).</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="GESL">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">GiltEdgedStockLendingAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Gilt Edged Stock Lending Agreement (GESLA).</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="KRSL">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">KoreanSecuritiesLendingAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Korean Securities Lending Agreement (KOSLA).</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="DERD">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">DeutscherRahmenvertragFurWertpapierdarlehen</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Deutscher Rahmenvertrag für Wertpapierdarlehen.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="AUSL">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">AustralianMastersSecuritiesLendingAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Australian Masters Securities Lending Agreement (AMSLA).</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="JPBL">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">JapaneseMasterAgreementOnLendingTransactionOfBonds</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Japanese Master Agreement on Lending Transaction of Bonds.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="JPSL">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">JapaneseMasterAgreementOnTheBorrowingAndLendingTransactionsOfShareCertificates</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Japanese Master Agreement on the Borrowing and Lending Transactions of Share Certificates.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="BIAG">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">BilateralAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Bilateral Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="CSDA">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CSD BilateralAgreement </xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">CSD Bilateral Agreement.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="OTHR">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Other</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Other typeif the master agreement type is not included in the list.</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max50Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max50Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 50 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max52Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max52Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 52 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="52"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="NaturalPersonIdentification2__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">NaturalPersonIdentification2__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Identifies a natural person through identification number, name and domicile.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="GenericIdentification175__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of the natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OrganisationIdentification15Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification15Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides the identification of the organisation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="LEI" type="LEIIdentifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">LEI</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification is done through the use of legal entity identifier code.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="PartyIdentification236Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PartyIdentification236Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides the identification of the organisation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="Lgl" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Legal</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Party is a legal person.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Ntrl" type="NaturalPersonIdentification2__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Natural</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Party is a natural person.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="SecuritiesFinancingReportingPairingRequestV02">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">SecuritiesFinancingReportingPairingRequestV02</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">The SecuritiesFinancingReportingPairingRequest is sent by the trade repository (TR) to the other trade repositories (TRs) in order to identify the trade repository (TR) holding information on a second leg of a given transaction.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" name="TxId" type="TradeTransactionIdentification15__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TransactionIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Set of information identifying the transactions that are to be paired.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TradeTransactionIdentification15__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">TradeTransactionIdentification15__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Provides details on transaction and conducting counterparty.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="RptgCtrPty" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">ReportingCounterparty</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code identifying the reporting counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="OthrCtrPty" type="PartyIdentification236Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OtherCounterparty</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique code identifying the entity with which the reporting counterparty concluded the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="UnqTradIdr" type="Max52Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">UniqueTradeIdentifier</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique trade Identifier (UTI) as agreed with the counterparty.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="MstrAgrmt" type="MasterAgreement7__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MasterAgreement</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Details related to the master agreement.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="AgtLndr" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">AgentLender</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of the agent lender involved in the securities lending transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="TrptyAgt" type="OrganisationIdentification15Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">TripartyAgent</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of the third party that administers the transaction.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
